### PR TITLE
Create Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by bergantine**
- Keeps compatibility back to Django 1.8
- Revised Travis config to use an installation matrix and tests for Python 3.6 and Django 2.0
- In the last pull request the Travis tests failed on a Tox install for Django 1.8 / Python 2.7; creating a new pull request as that appeared to be an anomaly

### CODE REVIEW

**Comment by bergantine** [comment]
Commits b3bc1f0, 4d6da6e, 9af7dcc, d163687, 98a2e4b combined resolve an issue encountered in Python 3.5 on Ubuntu Linux

```
Traceback (most recent call last):
   File "<string>", line 17, in <module>
   File "...../src/django-password-reset/setup.py", line 20, in <module>
     long_description=open('README.rst').read(),
   File "...../lib/python3.5/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 569: ordinal not in range(128)
```

**Comment by colelloa** [comment]
@brutasse is there any dev work that i can do that is preventing this from being merged?

**Comment by timgraham** [comment]
It's best to drop support for Django < 1.11 at this point (as done in https://github.com/brutasse/django-password-reset/pull/65).

**Comment by YiiKuoChong** [comment]
Why isn't this merged already?

**Comment by relwell** [comment]
It would be great to get this merged.

**Comment by timgraham** [comment]
I provided a patch in https://github.com/brutasse/django-password-reset/pull/72. I think you should submit the `UnicodeDecodeError` fix in a separate PR.

**Comment by brutasse** [comment]
Fixed in #72 and version 2.0

**Pull request closed without merging**
