### PR TITLE
[REVIEW] allowed override from calling app

### PR DESCRIPTION
**Pull request by rosscdh**
currently a number of settings cant be overridden.

implemented a simple pattern for providing required settings.

**main requriement**

was to be able to override the get_current_site method call as not all sites use the django.contrib.sites package

### CODE REVIEW

**Comment by brutasse** [comment]
`get_current_site` doesn't require the sites framework to be installed. It can return a `RequestSite` extracted from the HTTP request: https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#get-current-site-shortcut

Do you have issues with `get_current_site`?

**Comment by rosscdh** [comment]
Actually thats a good point. Not per se.. but I think for some reason the system has contrib.site and SITE_ID enabled.. but doesnt seem to use it. I'll double check.

PR could still stand, regarding overriding of the default 2 days expiry?

**Comment by brutasse** [comment]
Yes, but not with a settings lookup at import time. I'd add a method to the `Reset` class and change the `token_expires` attribute:

```python
token_expires = None

def get_token_expires(self):
    duration = getattr(settings, 'PASSWORD_RESET_TOKEN_EXPIRES', self.token_expires)
    if duration is None:
        duration = 3600 * 48
```

Then in the `dispatch()` method, use `self.get_token_expires()` instead of `self.token_expires`.

**Comment by rosscdh** [comment]
ok will do!

**Comment by rosscdh** [comment]
On second thought, then means that the view would have to be overridden. Which in itself is a valid use case but I was hoping to make it as light as possible.. ie. pip install add the settings dict and off we go.

**Comment by brutasse** [comment]
Hmm no, I have added https://github.com/brutasse/django-password-reset/commit/28bbe2e6323c6ed9d184285b3221686d58ece6ef which should be enough. A new version is available on PyPI, let me know how it works for you.

**Comment by rosscdh** [comment]
@brutasse ah thanks.. I was happy to do it just wanted to get your go ahead 👍 thanks

**Pull request closed without merging**
